---
- name: create the data store
  file: path="{{ elasticsearch_data_store_dir }}" state=directory

- name: start a Docker container to provide Elasticsearch
  docker:
    image: elasticsearch
    name: elasticsearch
    command: elasticsearch -Des.index.max_result_window=2147483647
    volumes: "{{ elasticsearch_data_store_dir }}:/usr/share/elasticsearch/data"
