---
- name: create the data store
  file: path="{{ redmine_data_store_dir }}" state=directory

- name: create the MySQL database
  mysql_db:
    login_host: "{{ mysql_host }}"
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{ redmine_database_name }}"
    collation: utf8_unicode_ci
    encoding: utf8
    state: present

- name: create the MySQL user
  mysql_user:
    login_host: "{{ mysql_host }}"
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{ redmine_database_user }}"
    host: "%"
    password: "{{ redmine_database_password }}"
    priv: "{{ redmine_database_name }}.*:SELECT,LOCK TABLES,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER"
    state: present

- name: start a Docker container to provide Redmine
  docker:
    image: sameersbn/redmine:2.6.1
    name: redmine
    ports: "127.0.0.1:{{ redmine_port_http }}:80"
    volumes: "{{ redmine_data_store_dir }}:/home/redmine/data"
    links: "mysql:mysql"
    env: "REDMINE_HTTPS=true,DB_TYPE=mysql,DB_NAME={{ redmine_database_name }},DB_USER={{ redmine_database_user }},DB_PASS={{ redmine_database_password }},SMTP_ENABLED=true,SMTP_HOST={{ smtp_host }},SMTP_PORT={{ smtp_port }},SMTP_DOMAIN={{ smtp_domain }},SMTP_STARTTLS=false"

- name: create a Self-Signed SSL Certificate
  command: openssl req -new -nodes -x509 -subj "/C={{ ssl_country }}/ST={{ ssl_locality }}/L={{ ssl_locality }}/O={{ ssl_organization }}/CN={{ redmine_server_name }}" -days {{ ssl_days }} -keyout {{ nginx_ssl_dir }}/redmine.key -out {{ nginx_ssl_dir }}/redmine.crt -extensions v3_ca creates={{ nginx_ssl_dir }}/redmine.crt
  notify: "restart Nginx"

- name: configure Nginx as a reverse proxy for Redmine
  template: src=../templates/nginx-redmine.j2 dest={{ nginx_site_enabled_dir }}/redmine
  notify: "restart Nginx"
