---
- name: install Python
  apt: pkg=python state=present

- name: be sure Python-pip is not installed
  apt: pkg=python-pip state=absent

- name: install Python-virtualenv
  apt: pkg=python-virtualenv state=present update_cache=yes

- name: install pip
  easy_install: name=pip
